import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Add node: prefixed versions of builtins for cloudflared and other packages
const nodeBuiltins = builtins.flatMap(m => [m, `node:${m}`]);

// Main plugin build
const mainContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
});

// Embedding worker build (separate bundle for Web Worker)
// Uses browser platform and ES2020 for BigInt support (required by ONNX)
const workerContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/embedding-worker.ts"],
	bundle: true,
	format: "iife",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "embedding-worker.js",
	platform: "browser",
	// Force WASM version of ONNX runtime
	conditions: ["browser", "import"],
	alias: {
		"onnxruntime-node": "onnxruntime-web",
	},
	// External native modules that can't be bundled
	external: [
		"*.node",
	],
});

if (prod) {
	await Promise.all([
		mainContext.rebuild(),
		workerContext.rebuild(),
	]);
	process.exit(0);
} else {
	await Promise.all([
		mainContext.watch(),
		workerContext.watch(),
	]);
}
